[features]
seeds = false
skip-lint = false
[programs.localnet]
agentsea_launchpad = "DZxHnHSzHfgoYd5qpjvxY67BRmS4Du6kjAZD5v4TPyWT"

[programs.devnet]
agentsea_launchpad = "DZxHnHSzHfgoYd5qpjvxY67BRmS4Du6kjAZD5v4TPyWT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
